-- MySQL Script generated by MySQL Workbench
-- 11/04/17 00:24:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cdc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cdc` (
  `idcdc` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `f_inicio` DATETIME NOT NULL,
  `f_fin` DATETIME NULL,
  `monto_final` INT NULL,
  PRIMARY KEY (`idcdc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ingreso` (
  `idingreso` INT NOT NULL AUTO_INCREMENT,
  `idcdc` INT NOT NULL,
  `monto` INT NULL,
  `n_factura` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `fecha_p` DATETIME NULL,
  `detalle` VARCHAR(100) NULL,
  PRIMARY KEY (`idingreso`),
  INDEX `fk_ingreso_cdc_idx` (`idcdc` ASC),
  CONSTRAINT `fk_ingreso_cdc`
    FOREIGN KEY (`idcdc`)
    REFERENCES `mydb`.`cdc` (`idcdc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`egreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`egreso` (
  `idegreso` INT NOT NULL AUTO_INCREMENT,
  `idcdc` INT NOT NULL,
  `monto` INT NULL,
  `n_factura` VARCHAR(45) NULL,
  `fecha` DATETIME NULL,
  `fecha_p` DATETIME NULL,
  `detalle` VARCHAR(100) NULL,
  PRIMARY KEY (`idegreso`),
  INDEX `fk_ingreso_cdc_idx` (`idcdc` ASC),
  CONSTRAINT `fk_ingreso_cdc0`
    FOREIGN KEY (`idcdc`)
    REFERENCES `mydb`.`cdc` (`idcdc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'admin' IDENTIFIED BY 'tempo123';

GRANT ALL ON `mydb`.* TO 'admin';
GRANT SELECT ON TABLE `mydb`.* TO 'admin';
GRANT SELECT, INSERT, TRIGGER ON TABLE `mydb`.* TO 'admin';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `mydb`.* TO 'admin';
GRANT EXECUTE ON ROUTINE `mydb`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
